language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# Two lines below needed for testing Py3.7: https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial
before_install:
  - sudo apt-get -qy update
  - sudo apt-get install -y tesseract-ocr
install: pip install .[test]
script: pytest
